# .github/workflows/mirror.yml
name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    - cron: '* 3 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      # - name: Mark GitHub workspace as safe
      #   run: |
      #     git config --global --add safe.directory /github/workspace
      - name: Mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v3
        with:
          origin: 'https://git.sr.ht/~bzg/org-contrib'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
