# .github/workflows/mirror.yml
name: 'mirror'
on:
#  push:
#    branches:
#      - __mirror
  schedule:
    # - cron: '42 3 * * *' ## 03:42
    - cron: '5 * * * *'
  # workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: Mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v3
        with:
          origin: 'https://git.sr.ht/~bzg/org-contrib'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
